//(function (){
	//设置表演 数据
	var performanceData = {//banner区域分类 演出数据
		ych:[//演唱会
				{
					tittle:"2017张杰“我想”世界巡回演唱会（厦门站）",
					price:"￥1280.00起",
					posterURL:"img/img_catalog_content/122770_n.jpg"
				},
				{
					tittle:"台湾云门舞集《稻禾》",
					price:"￥180.00起",
					posterURL:"img/img_catalog_content/125639_n.jpg"
				},
				{
					tittle:"美国百老汇原版音乐剧《修女也疯狂》",
					price:"￥180.00起",
					posterURL:"img/img_catalog_content/125635_n.jpg"
				},
				{
					tittle:"孟京辉多媒体音乐话剧《琥珀》",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/125401_n.jpg"
				}
			],
		yyh:[//音乐会
				{
					tittle:"《菊次郎的夏天》——久石让钢琴曲龙猫乐队梦幻之旅演奏会",
					price:"￥160.00起",
					posterURL:"img/img_catalog_content/125451_n.jpg"
				},
				
				{
					tittle:"八喜·2017打开艺术之门系列《周天羽钢琴音乐会》",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/125958_n.jpg"
				},
				{
					tittle:"2017年市民音乐会《美国亚利桑那男童合唱团音乐会》",
					price:"￥50.00起",
					posterURL:"img/img_catalog_content/125956_n.jpg"
				},
				{
					tittle:"意大利那不勒斯皇家爱乐乐团访华新年音乐会",
					price:"￥680.00起",
					posterURL:"img/img_catalog_content/127623_n.jpg"
				}
		],
		qyzt:[//曲艺杂坛
				{
					tittle:"“舞之狂欢节”—双钢琴音乐会",
					price:"￥180.00起",
					posterURL:"img/img_catalog_content/127620_n.jpg"
				},
				{
					tittle:"《久石让宫崎骏动漫视听—中国电影乐团音乐会》",
					price:"￥100.00起",
					posterURL:"img/img_catalog_content/125714_n.jpg"
				},
				
				{
					tittle:"电影20周年全球纪念版 爱尔兰踢踏舞剧《泰坦尼克号》",
					price:"￥380.00起",
					posterURL:"img/img_catalog_content/126474_n.jpg"
				}
		],
		hjgj:[//话剧歌剧
				{
					tittle:"CCTV国漫经典《猪猪侠之仙豆传奇》原版舞台剧",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/124424_n.jpg"
				},
			
				{
					tittle:"契诃夫戏剧《海鸥》-白俄罗斯扬卡库巴拉剧场",
					price:"￥50.00起",
					posterURL:"img/img_catalog_content/126714_n.jpg"
				},
				{
					tittle:"5D互动剧之“大话铁观音”",
					price:"￥98.00起",
					posterURL:"img/img_catalog_content/102397_n.jpg"
				}
				
		],
		tybs:[//体育比赛
				
				
		],
		wdbl:[//舞蹈芭蕾
				{
					tittle:"上海芭蕾舞蹈团《简·爱》",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/125645_n.jpg"
				},
				{
					tittle:"古典芭蕾舞剧《天鹅湖》",
					price:"￥280.00起",
					posterURL:"img/img_catalog_content/125626_n.jpg"
				},
				{
					tittle:"台湾林文中舞团《长河》",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/125630_n.jpg"
				},
				{
					tittle:"杨丽萍经典作品2017大型原生态歌舞集《云南映象》",
					price:"￥480.00起",
					posterURL:"img/img_catalog_content/126476_n.jpg"
				}
		],
		djxx:[//度假休闲
				{
					tittle:"厦门鼓浪屿贝壳梦幻世界",
					price:"￥25.00起",
					posterURL:"img/img_catalog_content/126600_n.jpg"
				},
				{
					tittle:"厦门魔法美术馆",
					price:"￥48.00起",
					posterURL:"img/img_catalog_content/125135_n.jpg"
				},
				{
					tittle:"厦门魔法美术馆",
					price:"￥48.00起",
					posterURL:"img/img_catalog_content/125135_n.jpg"
				}
		],
		etqz:[//儿童亲子
				
		],
		dm:[//动漫
				
		]
	};
	var toggleThreeData = {
		cnxh:[//猜您喜欢
				{
					tittle:"厦门鼓浪屿贝壳梦幻世界",
					price:"￥25.00起",
					posterURL:"img/img_catalog_content/126600_n.jpg"
				},
				{
					tittle:"厦门魔法美术馆",
					price:"￥48.00起",
					posterURL:"img/img_catalog_content/125135_n.jpg"
				},
				{
					tittle:"厦门魔法美术馆",
					price:"￥48.00起",
					posterURL:"img/img_catalog_content/125135_n.jpg"
				},
				{
					tittle:"台湾林文中舞团《长河》",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/125630_n.jpg"
				}
			],
		jrtj:[//今日推荐
				{
					tittle:"《菊次郎的夏天》——久石让钢琴曲龙猫乐队梦幻之旅演奏会",
					price:"￥160.00起",
					posterURL:"img/img_catalog_content/125451_n.jpg",
					site:"国家话剧院剧场",
					showDate:"2017.07.28"
				},
				
				{
					tittle:"八喜·2017打开艺术之门系列《周天羽钢琴音乐会》",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/125958_n.jpg",
					site:"国家话剧院剧场",
					showDate:"2017.07.28"
				},
				{
					tittle:"2017年市民音乐会《美国亚利桑那男童合唱团音乐会》",
					price:"￥50.00起",
					posterURL:"img/img_catalog_content/125956_n.jpg",
					site:"国家话剧院剧场",
					showDate:"2017.07.28"
				},
				{
					tittle:"意大利那不勒斯皇家爱乐乐团访华新年音乐会",
					price:"￥680.00起",
					posterURL:"img/img_catalog_content/127623_n.jpg",
					site:"国家话剧院剧场",
					showDate:"2017.07.28"
				},
				{
					tittle:"2017年市民音乐会《美国亚利桑那男童合唱团音乐会》",
					price:"￥50.00起",
					posterURL:"img/img_catalog_content/125956_n.jpg"
				},
				{
					tittle:"意大利那不勒斯皇家爱乐乐团访华新年音乐会",
					price:"￥680.00起",
					posterURL:"img/img_catalog_content/127623_n.jpg"
				}
			],
		yushou:[
				{
					tittle:"2017张杰“我想”世界巡回演唱会（厦门站）",
					price:"￥1280.00起",
					posterURL:"img/img_catalog_content/122770_n.jpg"
				},
				{
					tittle:"台湾云门舞集《稻禾》",
					price:"￥180.00起",
					posterURL:"img/img_catalog_content/125639_n.jpg"
				},
				{
					tittle:"美国百老汇原版音乐剧《修女也疯狂》",
					price:"￥180.00起",
					posterURL:"img/img_catalog_content/125635_n.jpg",
					site:"国家话剧院剧场",
					showDate:"2017.07.28"
				},
				{
					tittle:"孟京辉多媒体音乐话剧《琥珀》",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/125401_n.jpg"
				},
				{
					tittle:"CCTV国漫经典《猪猪侠之仙豆传奇》原版舞台剧",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/124424_n.jpg"
				},
				{
					tittle:"5D互动剧之“大话铁观音”",
					price:"￥98.00起",
					posterURL:"img/img_catalog_content/102397_n.jpg",
					site:"国家话剧院剧场",
					showDate:"2017.07.28"
				}
				,
				{
					tittle:"CCTV国漫经典《猪猪侠之仙豆传奇》原版舞台剧",
					price:"￥80.00起",
					posterURL:"img/img_catalog_content/124424_n.jpg"
				},
				{
					tittle:"5D互动剧之“大话铁观音”",
					price:"￥98.00起",
					posterURL:"img/img_catalog_content/102397_n.jpg",
					site:"国家话剧院剧场",
					showDate:"2017.07.28"
				}
			]
	};
	var rankingData = {//剧场排名数据
		smallTheater:[
					{
						rankingNumber:"1",
						name:"《那次奋不顾身的爱情》",
						rankingChange:"1"
					},
					{
						rankingNumber:"2",
						name:"《有多少爱可以胡来》",
						rankingChange:"1"
					},
					{
						rankingNumber:"3",
						name:"《一夜一生》",
						rankingChange:"1"
					},
					{
						rankingNumber:"4",
						name:"《傲慢与偏见》",
						rankingChange:"0"
					},
					{
						rankingNumber:"5",
						name:"《蠢蛋》",
						rankingChange:"1"
					},
					{
						rankingNumber:"6",
						name:"《九又二分之一爱情》",
						rankingChange:"1"
					},
					{
						rankingNumber:"7",
						name:"《谋杀歌谣》",
						rankingChange:"0"
					},
					{
						rankingNumber:"8",
						name:"《小王子》",
						rankingChange:"1"
					},
					{
						rankingNumber:"9",
						name:"《复你说我容易吗之—百万约定》",
						rankingChange:"1"
					},
					{
						rankingNumber:"10",
						name:"《最后作孽》",
						rankingChange:"1"
					},
					{
						rankingNumber:"11",
						name:"《傲慢与偏见》",
						rankingChange:"0"
					},
					{
						rankingNumber:"12",
						name:"《两只狗的生活意见》",
						rankingChange:"1"
					},
					{
						rankingNumber:"13",
						name:"《恋爱的犀牛》",
						rankingChange:"-1"
					},
					{
						rankingNumber:"14",
						name:"《最后晚餐》",
						rankingChange:"-1"
					},
					{
						rankingNumber:"15",
						name:"《坏老头的游戏》",
						rankingChange:"-1"
					}
				],
		bigTheater:[
					{
						rankingNumber:"1",
						name:"《李茶的姑妈》",
						rankingChange:"1"
					},
					{
						rankingNumber:"2",
						name:"《修女也疯狂》",
						rankingChange:"1"
					},
					{
						rankingNumber:"3",
						name:"《音乐之声》",
						rankingChange:"0"
					},
					{
						rankingNumber:"4",
						name:"《新月饭店》",
						rankingChange:"1"
					},
					{
						rankingNumber:"5",
						name:"《特洛伊》",
						rankingChange:"1"
					},
					{
						rankingNumber:"6",
						name:"《莎士比亚别生气》",
						rankingChange:"0"
					},
					{
						rankingNumber:"7",
						name:"《保镖》",
						rankingChange:"1"
					},
					{
						rankingNumber:"8",
						name:"《三体》",
						rankingChange:"1"
					},
					{
						rankingNumber:"9",
						name:"《高手》",
						rankingChange:"-1"
					},
					{
						rankingNumber:"10",
						name:"《战马》",
						rankingChange:"-1"
					}
				]
	};
	var floorData = {//楼层演出数据
		theater:[
					{
						name:"话剧《玩命爱一个姑娘》第十三轮",
						img:"img/floor/wmayggn.jpg",
						time:"2017.08.02-08.27",
						address:"北京西区剧场",
						price:"99",
						score:"8.0"
					},
					{
						name:"麦戏聚—多媒体3D舞台剧 盗墓笔记番外篇《新月饭店》",
						img:"img/floor/xyfd.jpg",
						time:"2017.10.14-10.15",
						address:"天桥剧场",
						price:"180",
						score:"8.0"
					},
					{
						name:"麦戏聚 孟京辉经典戏剧作品《恋爱的犀牛》 广州站",
						img:"img/floor/ladxn.jpg",
						time:"2017.10.13-10.14",
						address:"广州友谊剧院",
						price:"180",
						score:"8.0"
					},
					{
						name:"麦戏聚|多媒体3D舞台剧 告别演出版 《盗墓笔记Ⅱ：怒海潜沙》",
						img:"img/floor/dmbj.jpg",
						time:"2017.11.08-11.12",
						address:"人民大舞台",
						price:"180",
						score:"8.0"
					}
				],
		sports:[
					{
						name:"由奥瑞金赞助的2017NHL中国赛 北京站",
						img:"img/floor/nhlbjz.jpg",
						time:"2017.09.23",
						address:"五棵松体育馆",
						price:"160",
						score:"8.0"
					},
					{
						name:"2017武汉网球公开赛",
						img:"img/floor/whwqgks.jpg",
						time:"2017.09.22-2017.09.30",
						address:"光谷国际网球中心",
						price:"9.9",
						score:"8.0"
					},
					{
						name:"UFC 格斗之夜：上海",
						img:"img/floor/ufc.jpg",
						time:"2017.11.25",
						address:"梅赛德斯-奔驰文化中心",
						price:"252",
						score:"8.0"
					},
					{
						name:"2017中国足球协会甲级联赛深圳佳兆业主场赛事（深圳佳兆业VS浙江毅腾）",
						img:"img/floor/zqjjls.jpg",
						time:"2017.08.12",
						address:"深圳体育场",
						price:"30",
						score:"8.0"
					}
				],
		dance:[
					{
						name:"浪漫辉煌四十年-理查德·克莱德曼全球纪念巡演2018上海新年音乐会",
						img:"img/floor/lmhh.jpg",
						time:"2018.01.01",
						address:"梅赛德斯-奔驰文化中心",
						price:"180",
						score:"8.0"
					},
					{
						name:"德国海德堡爱乐乐团交响音乐会",
						img:"img/floor/dghdb.jpg",
						time:"2017.09.08",
						address:"大连人民文化俱乐部－大剧场",
						price:"120",
						score:"8.0"
					},
					{
						name:"爱无止境—奥斯卡获奖电影金曲精选音乐会",
						img:"img/floor/awzj.jpg",
						time:"2017.08.18",
						address:"上海音乐厅大厅",
						price:"100",
						score:"8.0"
					},
					{
						name:"爱乐汇•西班牙塞维利亚经典弗拉门戈舞剧《卡门》",
						img:"img/floor/km.jpg",
						time:"2017.09.28",
						address:"星海音乐厅（交响乐演奏厅）",
						price:"100",
						score:"8.0"
					}
				],
		children:[
					{
						name:"法国爆笑打击形体剧《回声超人》",
						img:"img/floor/hscr.jpg",
						time:"2017.08.17-08.20",
						address:"大麦·超剧场",
						price:"180",
						score:"8.0"
					},
					{
						name:"西班牙黑光机械舞秀《奇妙的机器人》BR2",
						img:"img/floor/brg.jpg",
						time:"2017.09.17",
						address:"正佳演艺剧院",
						price:"150",
						score:"8.0"
					},
					{
						name:"3D多媒体亲子音乐剧《绿野仙踪之奥兹国大冒险》",
						img:"img/floor/lyxz.jpg",
						time:"2017.09.16",
						address:"深圳市少年宫剧场",
						price:"80",
						score:"8.0"
					}
				],
		rockMusic:[
					{
						name:"伍佰&China Blue摇滚全经典之全面对决演唱会 深圳站",
						img:"img/floor/wbqmdj.jpg",
						time:"2017.08.26",
						address:"华润深圳湾体育中心＂春茧＂体育馆",
						price:"280",
						score:"8.0"
					},
					{
						name:"【Mr.】Mister Forever 狂热音乐会",
						img:"img/floor/kryyh.jpg",
						time:"2017.09.16",
						address:"深圳体育馆",
						price:"280",
						score:"8.0"
					},
					{
						name:"法国天使乐队爵士摇滚音乐会",
						img:"img/floor/fgtsydjsyg.jpg",
						time:"2017.08.18",
						address:"江西艺术中心音乐厅",
						price:"80",
						score:"8.0"
					},
					{
						name:"迈克学摇滚（爱永恒）中国巡演--广州站",
						img:"img/floor/mltr.jpg",
						time:"2017.08.20",
						address:"广州中山纪念堂",
						price:"280",
						score:"8.0"
					}
				]
	};
	var competitionsData = [//比赛排名数据
					{
						rankingNumber:"1",
						name:"2017 XCOMBO综合健身锦标赛—线上赛",
						address:"成都"
					},
					{
						rankingNumber:"2",
						name:"国际汽联F4中国锦标赛",
						address:"上海"
					},
					{
						rankingNumber:"3",
						name:"2017中国网球公开赛（莲花球场看台票）",
						address:"北京"
					},
					{
						rankingNumber:"4",
						name:"2017大连网球公开赛",
						address:"大连"
					},
					{
						rankingNumber:"5",
						name:"2017“第二届传奇巨星中国行”中葡足球对抗赛",
						address:"贵阳"
					},
					{
						rankingNumber:"6",
						name:"王者荣耀冠军杯暨暑期盛典总决赛",
						address:"成都"
					},
					{
						rankingNumber:"7",
						name:"佛山电台VR电竞大赛《V战成名》",
						address:"佛山"
					},
					{
						rankingNumber:"8",
						name:"2017U.I.M.F1摩托艇世界锦标赛中国哈尔滨大奖赛",
						address:"哈尔滨"
					},
					{
						rankingNumber:"9",
						name:"BIMBO Global Energy(宾堡环球健康跑)",
						address:"北京"
					},
					{
						rankingNumber:"10",
						name:"2017 WWE 经典美式摔跤娱乐秀--中国专场",
						address:"深圳"
					},
					{
						rankingNumber:"11",
						name:"2017 上海劳力士大师赛",
						address:"上海"
					},
					{
						rankingNumber:"12",
						name:"2017中国足球协会超级联赛天津亿利主场",
						address:"天津"
					}
				];
	var danceData = [//舞蹈数排名据
					{
						rankingNumber:"1",
						name:"中央芭蕾舞团 大型原创芭蕾舞剧《敦煌》全球首演",
						address:"北京"
					},
					{
						rankingNumber:"2",
						name:"“七夕”情人节《为你钟情》 张国荣影视金曲视听音乐会",
						address:"南宁"
					},
					{
						rankingNumber:"3",
						name:"2017亚洲指弹小王子松井佑贵中国巡演天津站",
						address:"天津"
					},
					{
						rankingNumber:"4",
						name:"星期广播音乐会:奏响金秋 收获硕果—上海大学音乐学院师生音乐会",
						address:"上海"
					},
					{
						rankingNumber:"5",
						name:"杨丽萍作品--大型原生态歌舞集《云南映象》",
						address:"上海"
					},
					{
						rankingNumber:"6",
						name:"“芭蕾航母”马林斯基首席舞者牵手乌克兰历史最悠久国家芭蕾舞团 倾情演绎《天鹅湖》《舞姬》",
						address:"成都"
					},
					{
						rankingNumber:"7",
						name:"挪威国宝级天团 神秘园(Secret Garden)中国巡演",
						address:"重庆"
					},
					{
						rankingNumber:"8",
						name:"浪漫辉煌四十年—理查德•克莱德曼2017北京圣诞音乐会",
						address:"北京"
					},
					{
						rankingNumber:"9",
						name:"爱乐汇•俄罗斯芭蕾国家剧院《睡美人》交响乐现场伴奏版",
						address:"上海"
					},
					{
						rankingNumber:"10",
						name:"麦小鹿：爱无止境—奥斯卡获奖电影金曲精选音乐会",
						address:"上海"
					}
				];
	var childrenData = [//儿童排名数据
					{
						rankingNumber:"1",
						name:"2017年春季巧虎大型舞台剧《蚂蚁王国历险记》广州站",
						address:"广州"
					},
					{
						rankingNumber:"2",
						name:"2017年秋冬巧虎大型舞台剧《消失的月光宝盒》广州站",
						address:"广州"
					},
					{
						rankingNumber:"3",
						name:"琥珀教育·陪你玩一夏 亲子舞台剧《超级飞侠—乐迪的秘密任务》",
						address:"广州"
					},
					{
						rankingNumber:"4",
						name:"快乐童年—2017马戏小丑嘉年华",
						address:"北京"
					},
					{
						rankingNumber:"5",
						name:"澳大利亚环球剧团科普互动偶剧《恐龙乐园》",
						address:"广州"
					},
					{
						rankingNumber:"6",
						name:"美国原版音乐舞台剧《爱探险的朵拉-海盗历险记》",
						address:"广州"
					},
					{
						rankingNumber:"7",
						name:"英国BBC大型动漫多媒体舞台剧《海底小纵队3：惊涛骇浪》—北京首演",
						address:"北京"
					},
					{
						rankingNumber:"8",
						name:"《大有不“童”国际绘本展》——百年绘本史&莫威廉世界",
						address:"广州"
					},
					{
						rankingNumber:"9",
						name:"第十届“打开艺术之门”暑期亲子系列 美国原版儿童音乐剧《爱探险的朵拉--海盗历险记》(中文版）",
						address:"深圳"
					},
					{
						rankingNumber:"10",
						name:"大型儿童人偶歌舞剧《尼尔斯骑鹅历险》",
						address:"广州"
					}
				];
	var rockMusicData = [//摇滚音乐排名数据
					{
						rankingNumber:"1",
						name:"2017 ONE NIGHT 给小孩演唱会",
						address:"北京"
					},
					{
						rankingNumber:"2",
						name:"陈奂仁 不求人大乐队音乐专场",
						address:"中山"
					},
					{
						rankingNumber:"3",
						name:"2017 半成品乐队中山巡演 ",
						address:"中山"
					},
					{
						rankingNumber:"4",
						name:"北京激流金属传奇乐队【ANCESTOR / 祖先】夏季巡演 西安站 ",
						address:"西安"
					},
					{
						rankingNumber:"5",
						name:"念乐队2017北方巡演 西安站 ",
						address:"西安"
					},
					{
						rankingNumber:"6",
						name:"亨伦·唐宫原著·星光音乐节 ",
						address:"石家庄"
					},
					{
						rankingNumber:"7",
						name:"伍佰&China Blue摇滚全经典之全面对决演唱会 深圳站 ",
						address:"深圳"
					},
					{
						rankingNumber:"8",
						name:"五月天LIFE《人生无限公司》2017 MAYDAY LIFE TOUR-北京站",
						address:"北京"
					}
				];

//})();
